### PR TITLE
updated contributing documentation

### PR DESCRIPTION
**Pull request by thekemkid**

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
:+1:

**Comment by thekemkid** [comment]
It's also worth linking to this pr over here: https://github.com/senecajs/seneca/pull/292

We might start adding a CONTRIBUTING.md to the base of every seneca repo so the contributing guidelines show up when creating PRs.

**Comment by AdrieanKhisbe** [comment]
@thekemkid.
Good Idea!
I suggest you to create a dedicated Issue to launch the connectino with a mention to @ senecajs/contributors

**Comment by thekemkid** [comment]
Oh, we might need to add a contribution tag for issues and pr's on this repo, as the core contrib guidelines now suggest opening contrib issues here, too! :)

**Pull request merged**
