### PR TITLE
initial versioned docs

### PR DESCRIPTION
**Pull request by matt-oc**
@mcdonnelldean Sorry it was a bit slow I was working on the website, Is this what you want?

#228 

The docs in v1 are the pre v2 commit state and the v2 ones are the current state

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@matt-oc Looks good, let me pull it down tomorrow and confirm.

**Comment by naomifeehanmoran** [comment]
@matt-oc looks like a good start to me, only thing is the path to images need to be updated, for example, the banner images
screen shot 2016-04-19 at 17 49 21

**Comment by matt-oc** [comment]
@naomifeehanmoran Yup will do that now, just wanted to see if that was the right track 😄

**Comment by matt-oc** [comment]
@naomifeehanmoran Can you review my change, because the image links come from a template they cant just be changed directly, happy to take advice on a better way of doing it.

**Comment by naomifeehanmoran** [comment]
thanks @matt-oc will take a look as soon as I have some time, @mcdonnelldean feel free to jump in if you can

**Comment by naomifeehanmoran** [comment]
@matt-oc @mcdonnelldean closing this as discussed with @mcdonnelldean we are putting versioning of docs on hold. Thanks for the work @matt-oc.

**Pull request closed without merging**
