### PR TITLE
Added TCS Logo

### PR DESCRIPTION
**Pull request by mcdonnelldean**
@AdrieanKhisbe Logo here, can you see if this looks ok? We have a PSD and TIFF to work with. I made an SVG but I don't know if it's going to come out ok or not.

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
svg looks ok

**Comment by AdrieanKhisbe** [comment]
shall Ii work on this branch before merging?

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe awesome, I'll merge this down so you can work away

**Comment by AdrieanKhisbe** [comment]
completed with a8afec0

**Pull request merged**
