### PR TITLE
Embeded contribute pages

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Solution to #128

Used [stree](http://tdd.github.io/git-stree/) to embed `contrib` content

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean  @rjrodger @orlacoding feedback welcome.
I don't want to self merge this important PR :)

**Comment by geek** [comment]
@AdrieanKhisbe this is awesome, love this approach.  Now we need to decide if we want to even have contrib copies or if the contrib copies should just link here?

**Comment by AdrieanKhisbe** [comment]
(=

I dont really see what the alternatives are. :/
You mean replace contrib repo with folder under Seneca?

**Comment by geek** [comment]
Like this: https://github.com/senecajs/contrib/blob/master/governance.md

**Comment by AdrieanKhisbe** [comment]
mmmmm.
The idea was that contrib lives on its own, and tat seneca.org embed them.

Maybe then would be better to have a subrepo (I just discoverd this 2 seconds)
https://github.com/ingydotnet/git-subrepo

**Comment by geek** [comment]
Either way, I am fine with everything in https://github.com/senecajs/senecajs.org/tree/master/src/pages/contribute/details being what we maintain.  Can you get the subrepo to work with our contrib repo?

**Comment by mcdonnelldean** [comment]
@geek @AdrieanKhisbe This seems a lot of effort. The original idea of the contrib repo was before we had a site. Why not just move everything to one repo and be done with it? One less repo to maintain.

Good work btw @AdrieanKhisbe

**Comment by AdrieanKhisbe** [comment]
thought some would have prefer a contrib repo. (and didn't know it predated the website)
In that case we can say *farewell contrib repo* :)

And thanks @mcdonnelldean :smiley:

**Comment by geek** [comment]
@mcdonnelldean sounds good, I will delete /contrib this week.

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe @geek Awesome stuff. Ok back to my hidey hole, cya all in the new year.

**Comment by AdrieanKhisbe** [comment]
hehe. :fireworks: 
enjoy @mcdonnelldean

**Pull request merged**
