### PR TITLE
Export and Pin API docs

### PR DESCRIPTION
**Pull request by kamil-mech**
https://github.com/senecajs/senecajs.org/issues/170

I'm open to suggestions. The remainder will be done tomorrow.

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Excellent job @kamil-mech ! :smiley: 

I have two enhancement suggesstions, but since they need to be applied document to the whole document, I can take care of this.
(secify js for markdown bloc. Use `####`  heading level for examples)

**Comment by AdrieanKhisbe** [comment]
@kamil-mech @mcdonnelldean Good to merge?

@kamil-mech , you mention remainder? did you mean of the Api doc?
(in that case, no problem to merge and do a dedicated PR for the commands)

**Comment by kamil-mech** [comment]
@AdrieanKhisbe I will continue on with the API docs (new PR later) and also implement your suggestions.

Also I noticed an inconsistency where in Getting Started the params for `add` are `msg` and `respond`, whereas in API they are called `args` and `cb`

Should I standardise? If yes, which should I go with?

**Comment by mcdonnelldean** [comment]
go with msg, done

**Comment by kamil-mech** [comment]
Cool! It will be shipped with the next PR

**Pull request merged**
