### PR TITLE
Seneca with Promises Tutorial

### PR DESCRIPTION
**Pull request by blainsmith**
As "promised", here is the tutorial. :wink:

### CODE REVIEW

**Comment by geek** [comment]
Well done, very easy to follow.

**Comment by blainsmith** [comment]
Thanks!

**Comment by mcdonnelldean** [comment]
@blainsmith Awesome, I'll get this on to the live site today (GMT)

**Comment by paulovieira** [comment]
Nice tutorial! However there is one important API change in the new version of Bluebird which make the code in the tutorial unusable. I submitted a pull request about this.

**Comment by blainsmith** [comment]
Nice work! Thanks!

**Pull request merged**
