### PR TITLE
New design

### PR DESCRIPTION
**Pull request by thefoxis**
* optimised graphics
* using SVG wherever possible
* no icon fonts
* no Bootstrap
* componentized
* cleaned up HTML in templates
* from **4.23s load, 701KB** to **1s load, 387KB**

please review @mcdonnelldean :tada:

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
Woah! That's some time difference in load time!

It looks epic, love all the little refinements, very tidy stuff indeed.

I've had a review of the changes, notes below.

### Splash - Banner
- Can we make the icons white
- Icons need to be smaller (use space to increase npm callout)
- Last icon doesn't fit the theme 'organise', perhaps stacked blocks?
- npm install call to action needs to be larger
- overall banner height is good, stick with it through size changes
- Needs drop shadow on bottom, like previous design.

### Splash - Examples
- Remove 'Example:' text
- Remove all caps style from example headers
- This section doesn't flow right but I'm lost on how to improve that, thoughts?

### Footer
- Missing top shadow that overlays onto footer banner (like previous design)

### Search - On Mobile
- Can we make the search occupy the free space to the left of the menu button. It looks squashed

### Mobile
- On mobile, some of the styling looks wrong. For instance the Getting Started page has some space to the right on my iPhone. It's like a padding of 20ish pixels on the right side of the page (doesn't affect sticky menu)
- On mobile, H2 and H1 look like they have their styles reversed, H1's are small and H2's are larger)
- On mobile, inline code has line height issues, the content and fill are dropped below the baseline of the regular text.

### Section icon
- Style so it appears in the gutter (Heading should line up with body text)
- Make it bigger overall but deemphasis so it's not as jarring,  (grey maybe?)

### Code Examples
- Where we have example code we have a little tag description underneath. Can we style this so it is closer to the code above so that they group visually?

Site is live here for anyone that wants to see the progress.

http://seneca-test.surge.sh/

**Comment by AdrieanKhisbe** [comment]
Good work @thefoxis 

Few remarks though:
-  I really liked the old icons and orange color (above all person with brain gear!! :))
- there is a glitch induse by the header when you go to a fragment: the header is header by banner
  ex: http://seneca-test.surge.sh/tutorials/#nodezoo
- Few style remark, where I preferred old design (had them side by side). (personal point of few)
  - code `styling`: old one what rather cool, red like.
  - bottom footer copyright in dark grey was cool
  - search box feel weird with the border. l

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe 

- Old icons stuck out from the rest of the brand, they had to go
- We are trying to lighten the page feel a little

**Comment by mcdonnelldean** [comment]
@thefoxis Love the new illustration! +1

**Comment by AdrieanKhisbe** [comment]
I like better indeed ! :)

**Comment by thefoxis** [comment]
With regards to:

>  This section doesn't flow right but I'm lost on how to improve that, thoughts?

Not much I can do in terms of layout as it's pulled from markdown so even making it two columns is impossible unless you want HTML in markdown source @mcdonnelldean.

Fixing remaining code snippets issues :)

**Comment by mcdonnelldean** [comment]
@thefoxis I think when you styled the code boxes to go full page the problem sort of fixed itself :D They sit much better now. :D Couple of notes:

- Logging tutorial page has a right padding issue, but only on iOS that I can see, ideas?
- Code looks much better now on the bigger articles as full width but on mobile the code doesn't scroll horizontally anymore, instead it flows like a paragraph.
- Can we decrease the size of the non splash page banner and footer banner by 1/3rd, just to make
them less imposing.
- I don't see any changes to the section character, The notes above for the section relate to this little thing ( § )

I'll push this PR live tonight as it's pretty much done :D I'll move the notes about out into separate issues too so they can be worked on as lower priority. 

Super work though, very very nice!

**Comment by mcdonnelldean** [comment]
Merging in work so far :fireworks:

**Pull request merged**
