### PR TITLE
Add docs for plugin init

### PR DESCRIPTION
**Pull request by kamil-mech**
https://github.com/senecajs/senecajs.org/issues/164

Also https://github.com/senecajs/seneca/pull/329

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
@kamil-mech  good to me, :smiley: 
but Might be the occasion to replace html syntax for link with `[markdown](one)`

**Comment by kamil-mech** [comment]
You mean like this?

```
[markdown](how-to-write-a-plugin.html#wp-init)
```

**Comment by AdrieanKhisbe** [comment]
just using the fragment will be enough :smiley:
`[Initialize a Plugin](#wp-init)`

**Comment by kamil-mech** [comment]
Also, I don't see this doing anything. Should I remove?
```
<small style="float:right"><a href="#how-to-write-a-seneca-plugin">[top]</a></small>
```

**Comment by AdrieanKhisbe** [comment]
for sure :)

**Comment by kamil-mech** [comment]
Is that satisfactory? :)

**Comment by AdrieanKhisbe** [comment]
almost :)
just one `<a href="#wp-name">Give Your Plugin a Name</a>` slip throught.

after you _amend push force_, it's good to me. :)

@mcdonnelldean, good for you?

**Comment by kamil-mech** [comment]
Done!

Waiting for Dean

**Comment by mcdonnelldean** [comment]
@kamil-mech Very impressive! Good job.

**Comment by AdrieanKhisbe** [comment]
:clap: :+1:

**Pull request merged**
